# Generated by Django 3.2.17 on 2023-03-14 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_num', models.IntegerField(default=0, verbose_name='Number of shows')),
                ('already_learn', models.BooleanField(default=False, verbose_name='Learned')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Английское слово',
                'verbose_name_plural': 'Английские слова',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_word', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='English word')),
                ('ru_word', models.CharField(blank=True, max_length=50, verbose_name='Russian translation')),
                ('ru_word_optional', models.CharField(blank=True, max_length=50, verbose_name='Additional russian translation')),
                ('users', models.ManyToManyField(through='english.UserWord', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Английское слово',
                'verbose_name_plural': 'Английские слова',
                'ordering': ['en_word'],
            },
        ),
        migrations.AddField(
            model_name='userword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.word'),
        ),
    ]
