# Generated by Django 3.2.17 on 2023-04-04 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='already_learn',
            field=models.BooleanField(default=False, verbose_name='Learned'),
        ),
        migrations.AddField(
            model_name='word',
            name='show_num',
            field=models.IntegerField(default=0, verbose_name='Number of shows'),
        ),
        migrations.AddField(
            model_name='word',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('en_word', 'user')},
        ),
        migrations.RemoveField(
            model_name='word',
            name='users',
        ),
        migrations.DeleteModel(
            name='UserWord',
        ),
    ]
