# Generated by Django 3.2.17 on 2023-02-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='ru_word_optional',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='word',
            name='ru_word',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
