# Generated by Django 3.2.17 on 2023-04-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_auto_20230404_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='en_word',
            field=models.CharField(db_index=True, max_length=50, verbose_name='English word'),
        ),
    ]
