# Generated by Django 3.2.17 on 2023-02-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_auto_20230222_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='already_learn',
            field=models.BooleanField(default=False),
        ),
    ]
