# Generated by Django 3.2.17 on 2023-03-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_alter_word_already_learn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['en_word'], 'verbose_name': 'Английские слова', 'verbose_name_plural': 'Английские слова'},
        ),
        migrations.AlterField(
            model_name='word',
            name='already_learn',
            field=models.BooleanField(default=False, verbose_name='Learned'),
        ),
        migrations.AlterField(
            model_name='word',
            name='en_word',
            field=models.CharField(max_length=50, verbose_name='English word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='ru_word',
            field=models.CharField(blank=True, max_length=50, verbose_name='Russian translation'),
        ),
        migrations.AlterField(
            model_name='word',
            name='ru_word_optional',
            field=models.CharField(blank=True, max_length=50, verbose_name='Additional russian translation'),
        ),
        migrations.AlterField(
            model_name='word',
            name='show_num',
            field=models.IntegerField(default=0, verbose_name='Number of shows'),
        ),
    ]
